name: notion
description: "A Productivity Application."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.1.0
  firebase_ai: ^3.2.0
  flutter_bloc: ^9.1.1
  genkit: ^0.5.1
  http: ^1.5.0
  get_it: ^8.2.0
  shared_preferences: ^2.5.3
  equatable: ^2.0.7
  lucide_icons: ^0.257.0
  bloc: ^9.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true